//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Global/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""cef9b0c8-1594-4321-a37c-8af094058484"",
            ""actions"": [
                {
                    ""name"": ""ButtonTriangle"",
                    ""type"": ""Button"",
                    ""id"": ""a9575ec4-f783-4f30-9027-be61f9182d67"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ButtonCircle"",
                    ""type"": ""Button"",
                    ""id"": ""95fa4a79-d53a-4944-8d2a-94a2e6faf907"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ButtonCross"",
                    ""type"": ""Button"",
                    ""id"": ""ff06369e-aac9-48b9-9660-83f7c31b23bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ButtonSquare"",
                    ""type"": ""Button"",
                    ""id"": ""d71f681a-ee8a-4b0d-952a-eef940cddabb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ButtonL1"",
                    ""type"": ""Button"",
                    ""id"": ""eac21493-fd5f-4d56-9d69-0ee7f8750aba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ButtonR1"",
                    ""type"": ""Button"",
                    ""id"": ""6b97a722-da94-4110-a9c3-590577bdf07b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ButtonStart"",
                    ""type"": ""Button"",
                    ""id"": ""13b7f8fc-55f3-4989-876a-950dbdc088c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugSong"",
                    ""type"": ""Button"",
                    ""id"": ""33de52aa-08bc-4abb-a860-8d9d787be5b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugMenu"",
                    ""type"": ""Button"",
                    ""id"": ""78a7de17-5aa9-482b-ab71-5cbb1a38e9c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugMetronome"",
                    ""type"": ""Button"",
                    ""id"": ""670dcca3-af5a-4d1b-a8ba-d6f097023811"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f264cac5-a222-4512-8d55-94acf561af2c"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonTriangle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c17171fa-5594-4f22-a8e8-8c9794630459"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonTriangle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df593bd5-03a3-4f4f-af6d-d13bc437c9e4"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonCircle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92ad35d1-0076-4f4f-9d45-bef13b20a37a"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonCircle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3b5578d-2c08-4261-9de9-1bcf8c4f7bd7"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonCross"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a618a79-0cfa-49ef-aaa6-09002fc3e881"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonCross"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a3de67e-8fbe-4559-9c92-defd36b7802d"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonSquare"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""520ddb0d-683b-4d15-8c49-7b56d47b415c"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonSquare"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a418effb-a22b-41bd-95c9-f8234dfa3778"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonL1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6079e95e-66f2-469a-a4e6-505ff87d5c2a"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonL1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2973f15-1702-4ee5-bc0b-2e4a2fd98c60"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonR1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""495ec3b7-29f0-4fc6-b11f-b99863d1a7b5"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonR1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b8ea857-58d6-4ecc-b2a4-38db70859e76"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b0b31c5-0e79-4e08-baad-0b5bb29c11f5"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cd63ce6-af17-4f00-8d6a-4993d77d3e35"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugSong"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa55d097-c221-4aed-bd45-cca6844fd7aa"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bdb8c325-ccfb-4c55-8d94-085305be70ce"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugMetronome"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_ButtonTriangle = m_Gameplay.FindAction("ButtonTriangle", throwIfNotFound: true);
        m_Gameplay_ButtonCircle = m_Gameplay.FindAction("ButtonCircle", throwIfNotFound: true);
        m_Gameplay_ButtonCross = m_Gameplay.FindAction("ButtonCross", throwIfNotFound: true);
        m_Gameplay_ButtonSquare = m_Gameplay.FindAction("ButtonSquare", throwIfNotFound: true);
        m_Gameplay_ButtonL1 = m_Gameplay.FindAction("ButtonL1", throwIfNotFound: true);
        m_Gameplay_ButtonR1 = m_Gameplay.FindAction("ButtonR1", throwIfNotFound: true);
        m_Gameplay_ButtonStart = m_Gameplay.FindAction("ButtonStart", throwIfNotFound: true);
        m_Gameplay_DebugSong = m_Gameplay.FindAction("DebugSong", throwIfNotFound: true);
        m_Gameplay_DebugMenu = m_Gameplay.FindAction("DebugMenu", throwIfNotFound: true);
        m_Gameplay_DebugMetronome = m_Gameplay.FindAction("DebugMetronome", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_Gameplay_ButtonTriangle;
    private readonly InputAction m_Gameplay_ButtonCircle;
    private readonly InputAction m_Gameplay_ButtonCross;
    private readonly InputAction m_Gameplay_ButtonSquare;
    private readonly InputAction m_Gameplay_ButtonL1;
    private readonly InputAction m_Gameplay_ButtonR1;
    private readonly InputAction m_Gameplay_ButtonStart;
    private readonly InputAction m_Gameplay_DebugSong;
    private readonly InputAction m_Gameplay_DebugMenu;
    private readonly InputAction m_Gameplay_DebugMetronome;
    public struct GameplayActions
    {
        private @PlayerControls m_Wrapper;
        public GameplayActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @ButtonTriangle => m_Wrapper.m_Gameplay_ButtonTriangle;
        public InputAction @ButtonCircle => m_Wrapper.m_Gameplay_ButtonCircle;
        public InputAction @ButtonCross => m_Wrapper.m_Gameplay_ButtonCross;
        public InputAction @ButtonSquare => m_Wrapper.m_Gameplay_ButtonSquare;
        public InputAction @ButtonL1 => m_Wrapper.m_Gameplay_ButtonL1;
        public InputAction @ButtonR1 => m_Wrapper.m_Gameplay_ButtonR1;
        public InputAction @ButtonStart => m_Wrapper.m_Gameplay_ButtonStart;
        public InputAction @DebugSong => m_Wrapper.m_Gameplay_DebugSong;
        public InputAction @DebugMenu => m_Wrapper.m_Gameplay_DebugMenu;
        public InputAction @DebugMetronome => m_Wrapper.m_Gameplay_DebugMetronome;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @ButtonTriangle.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonTriangle;
                @ButtonTriangle.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonTriangle;
                @ButtonTriangle.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonTriangle;
                @ButtonCircle.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonCircle;
                @ButtonCircle.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonCircle;
                @ButtonCircle.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonCircle;
                @ButtonCross.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonCross;
                @ButtonCross.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonCross;
                @ButtonCross.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonCross;
                @ButtonSquare.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonSquare;
                @ButtonSquare.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonSquare;
                @ButtonSquare.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonSquare;
                @ButtonL1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonL1;
                @ButtonL1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonL1;
                @ButtonL1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonL1;
                @ButtonR1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonR1;
                @ButtonR1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonR1;
                @ButtonR1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonR1;
                @ButtonStart.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonStart;
                @ButtonStart.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonStart;
                @ButtonStart.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnButtonStart;
                @DebugSong.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDebugSong;
                @DebugSong.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDebugSong;
                @DebugSong.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDebugSong;
                @DebugMenu.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDebugMenu;
                @DebugMenu.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDebugMenu;
                @DebugMenu.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDebugMenu;
                @DebugMetronome.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDebugMetronome;
                @DebugMetronome.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDebugMetronome;
                @DebugMetronome.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDebugMetronome;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ButtonTriangle.started += instance.OnButtonTriangle;
                @ButtonTriangle.performed += instance.OnButtonTriangle;
                @ButtonTriangle.canceled += instance.OnButtonTriangle;
                @ButtonCircle.started += instance.OnButtonCircle;
                @ButtonCircle.performed += instance.OnButtonCircle;
                @ButtonCircle.canceled += instance.OnButtonCircle;
                @ButtonCross.started += instance.OnButtonCross;
                @ButtonCross.performed += instance.OnButtonCross;
                @ButtonCross.canceled += instance.OnButtonCross;
                @ButtonSquare.started += instance.OnButtonSquare;
                @ButtonSquare.performed += instance.OnButtonSquare;
                @ButtonSquare.canceled += instance.OnButtonSquare;
                @ButtonL1.started += instance.OnButtonL1;
                @ButtonL1.performed += instance.OnButtonL1;
                @ButtonL1.canceled += instance.OnButtonL1;
                @ButtonR1.started += instance.OnButtonR1;
                @ButtonR1.performed += instance.OnButtonR1;
                @ButtonR1.canceled += instance.OnButtonR1;
                @ButtonStart.started += instance.OnButtonStart;
                @ButtonStart.performed += instance.OnButtonStart;
                @ButtonStart.canceled += instance.OnButtonStart;
                @DebugSong.started += instance.OnDebugSong;
                @DebugSong.performed += instance.OnDebugSong;
                @DebugSong.canceled += instance.OnDebugSong;
                @DebugMenu.started += instance.OnDebugMenu;
                @DebugMenu.performed += instance.OnDebugMenu;
                @DebugMenu.canceled += instance.OnDebugMenu;
                @DebugMetronome.started += instance.OnDebugMetronome;
                @DebugMetronome.performed += instance.OnDebugMetronome;
                @DebugMetronome.canceled += instance.OnDebugMetronome;
            }
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnButtonTriangle(InputAction.CallbackContext context);
        void OnButtonCircle(InputAction.CallbackContext context);
        void OnButtonCross(InputAction.CallbackContext context);
        void OnButtonSquare(InputAction.CallbackContext context);
        void OnButtonL1(InputAction.CallbackContext context);
        void OnButtonR1(InputAction.CallbackContext context);
        void OnButtonStart(InputAction.CallbackContext context);
        void OnDebugSong(InputAction.CallbackContext context);
        void OnDebugMenu(InputAction.CallbackContext context);
        void OnDebugMetronome(InputAction.CallbackContext context);
    }
}
